# Generated by Django 5.2 on 2025-11-29 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_configuracionempresa_alertas_config'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendar',
            options={'ordering': ['empresa', 'name'], 'verbose_name': 'calendar', 'verbose_name_plural': 'calendars'},
        ),
        migrations.AddField(
            model_name='calendar',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que pertenece este calendario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendarios', to='Clientes.configuracionempresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='slug'),
        ),
        migrations.AlterUniqueTogether(
            name='calendar',
            unique_together={('empresa', 'slug')},
        ),
    ]
